[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd backend && npm ci --only=production --no-audit --no-fund"
]

[phases.build]
cmds = [
  "echo 'Frontend already built locally'"
]

[start]
cmd = "cd backend && npm start"
