[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "npm ci --only=production --no-audit --no-fund --prefer-offline",
  "npm --prefix frontend ci --only=production --no-audit --no-fund --prefer-offline"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build --mode production"
]

[start]
cmd = "cd backend && npm start"
