[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --only=production --no-audit --no-fund",
  "npm --prefix frontend ci --only=production --no-audit --no-fund"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build"
]

[start]
cmd = "cd backend && npm start"
